from decimal import Decimal


def test_invoice_amount_tolerance_rule_example() -> None:
    po_amount = Decimal("10000.00")
    invoice_amount = Decimal("11500.00")
    variance = abs(invoice_amount - po_amount) / po_amount

    assert variance == Decimal("0.15")
    assert variance > Decimal("0.05")


def test_seed_counts_are_positive() -> None:
    # Contract for the synthetic dataset generated by database.seed.
    from database.seed import INVOICE_COUNT, PO_COUNT, VENDOR_COUNT

    assert VENDOR_COUNT == 25
    assert PO_COUNT == 100
    assert INVOICE_COUNT == 150
