CREATE TABLE IF NOT EXISTS vendors (
    vendor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    payment_terms VARCHAR(100),
    risk_score NUMERIC(5, 4) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    po_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id INTEGER NOT NULL REFERENCES vendors(vendor_id),
    po_number VARCHAR(100) NOT NULL UNIQUE,
    total_amount NUMERIC(14, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN'
);

CREATE TABLE IF NOT EXISTS invoices (
    invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id INTEGER REFERENCES vendors(vendor_id),
    invoice_number VARCHAR(100) NOT NULL,
    po_number VARCHAR(100),
    amount NUMERIC(14, 2),
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    raw_text TEXT
);

CREATE TABLE IF NOT EXISTS agent_decisions (
    decision_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES invoices(invoice_id),
    decision VARCHAR(50) NOT NULL,
    confidence NUMERIC(5, 4),
    reasoning TEXT,
    requires_human BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    node_name VARCHAR(100) NOT NULL,
    input_snapshot JSONB,
    output_snapshot JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invoices_po_number ON invoices(po_number);
CREATE INDEX IF NOT EXISTS idx_invoices_vendor_id ON invoices(vendor_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_audit_logs_invoice_id ON audit_logs(invoice_id);
